# Generated by Django 5.1.2 on 2024-12-30 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_cumpleaños', models.DateField(blank=True, null=True)),
                ('pregunta1', models.CharField(blank=True, max_length=255, null=True)),
                ('pregunta2', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta1', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta2', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
