# Generated by Django 5.1.2 on 2024-11-04 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_registro',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='vendedor',
            new_name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pago_anticipado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_cumpleanos',
            field=models.DateField(default=datetime.date(2024, 11, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('anticipado', 'Pago Anticipado'), ('contraentrega', 'Contra Entrega')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_vendedor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
