# Generated by Django 5.1.2 on 2024-11-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nombre_vendedor',
            field=models.CharField(choices=[('John', 'John Jimenez'), ('Johanna', 'Johanna García'), ('Tatiana', 'Tatiana Rengifo')], max_length=100),
        ),
    ]
