# Generated by Django 5.1.2 on 2024-11-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedido_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('anticipado', 'Pago Anticipado'), ('contraentrega', 'Contra Entrega')], default='Contra Entrega', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_vendedor',
            field=models.CharField(choices=[('John', 'John Jimenez'), ('Johanna', 'Johanna García'), ('Tatiana', 'Tatiana Rengifo'), ('Tienda Virtual', 'Tienda Virtual')], default='Tienda Virtual', max_length=100),
        ),
    ]
