# Generated by Django 5.1.2 on 2024-11-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_metodo_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_cumpleanos',
        ),
    ]
