# Generated by Django 5.1.2 on 2024-12-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_remove_pedido_fecha_cumpleanos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.CharField(choices=[('Frutos Rojos', 'Frutos Rojos'), ('Batido Verde', 'Batido Verde')], default='Batido Verde', max_length=20),
        ),
    ]
