# Generated by Django 5.1.2 on 2024-12-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='gano_ruleta',
            field=models.BooleanField(default=False),
        ),
    ]
