# Generated by Django 5.1.2 on 2024-12-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_pedido_gano_ruleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='gano_ruleta',
        ),
    ]
