# Generated by Django 5.1.2 on 2024-12-15 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0010_remove_pedido_gano_ruleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoRuleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('Descuento 10%', 'Descuento 10%'), ('Descuento 20%', 'Descuento 20%'), ('Envío Gratis', 'Envío Gratis'), ('Sin Premio', 'Sin Premio')], max_length=50)),
                ('fecha_giro', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_ruleta', to='pedidos.pedido')),
            ],
        ),
    ]
