# Generated by Django 5.1.2 on 2024-11-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='fecha',
            new_name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='libras',
        ),
        migrations.AddField(
            model_name='compra',
            name='cantidad_libras',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='nombre_ingrediente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
